HEADERS += \
    $$PWD/external/clara.h \
    $$PWD/external/tbc_text_format.h \
    $$PWD/internal/catch_approx.hpp \
    $$PWD/internal/catch_assertionresult.h \
    $$PWD/internal/catch_assertionresult.hpp \
    $$PWD/internal/catch_capture.hpp \
    $$PWD/internal/catch_clara.h \
    $$PWD/internal/catch_commandline.hpp \
    $$PWD/internal/catch_common.h \
    $$PWD/internal/catch_common.hpp \
    $$PWD/internal/catch_compiler_capabilities.h \
    $$PWD/internal/catch_config.hpp \
    $$PWD/internal/catch_console_colour.hpp \
    $$PWD/internal/catch_console_colour_impl.hpp \
    $$PWD/internal/catch_context.h \
    $$PWD/internal/catch_context_impl.hpp \
    $$PWD/internal/catch_debugger.h \
    $$PWD/internal/catch_debugger.hpp \
    $$PWD/internal/catch_default_main.hpp \
    $$PWD/internal/catch_evaluate.hpp \
    $$PWD/internal/catch_exception_translator_registry.hpp \
    $$PWD/internal/catch_expression_lhs.hpp \
    $$PWD/internal/catch_fatal_condition.hpp \
    $$PWD/internal/catch_generators.hpp \
    $$PWD/internal/catch_generators_impl.hpp \
    $$PWD/internal/catch_impl.hpp \
    $$PWD/internal/catch_interfaces_capture.h \
    $$PWD/internal/catch_interfaces_config.h \
    $$PWD/internal/catch_interfaces_exception.h \
    $$PWD/internal/catch_interfaces_generators.h \
    $$PWD/internal/catch_interfaces_registry_hub.h \
    $$PWD/internal/catch_interfaces_reporter.h \
    $$PWD/internal/catch_interfaces_runner.h \
    $$PWD/internal/catch_interfaces_tag_alias_registry.h \
    $$PWD/internal/catch_interfaces_testcase.h \
    $$PWD/internal/catch_legacy_reporter_adapter.h \
    $$PWD/internal/catch_legacy_reporter_adapter.hpp \
    $$PWD/internal/catch_list.hpp \
    $$PWD/internal/catch_matchers.hpp \
    $$PWD/internal/catch_matchers_string.h \
    $$PWD/internal/catch_matchers_string.hpp \
    $$PWD/internal/catch_matchers_vector.h \
    $$PWD/internal/catch_message.h \
    $$PWD/internal/catch_message.hpp \
    $$PWD/internal/catch_notimplemented_exception.h \
    $$PWD/internal/catch_notimplemented_exception.hpp \
    $$PWD/internal/catch_objc.hpp \
    $$PWD/internal/catch_objc_arc.hpp \
    $$PWD/internal/catch_option.hpp \
    $$PWD/internal/catch_platform.h \
    $$PWD/internal/catch_ptr.hpp \
    $$PWD/internal/catch_reenable_warnings.h \
    $$PWD/internal/catch_registry_hub.hpp \
    $$PWD/internal/catch_reporter_registrars.hpp \
    $$PWD/internal/catch_reporter_registry.hpp \
    $$PWD/internal/catch_result_builder.h \
    $$PWD/internal/catch_result_builder.hpp \
    $$PWD/internal/catch_result_type.h \
    $$PWD/internal/catch_run_context.hpp \
    $$PWD/internal/catch_section.h \
    $$PWD/internal/catch_section.hpp \
    $$PWD/internal/catch_section_info.h \
    $$PWD/internal/catch_section_info.hpp \
    $$PWD/internal/catch_stream.h \
    $$PWD/internal/catch_stream.hpp \
    $$PWD/internal/catch_streambuf.h \
    $$PWD/internal/catch_suppress_warnings.h \
    $$PWD/internal/catch_tag_alias.h \
    $$PWD/internal/catch_tag_alias_registry.h \
    $$PWD/internal/catch_tag_alias_registry.hpp \
    $$PWD/internal/catch_test_case_info.h \
    $$PWD/internal/catch_test_case_info.hpp \
    $$PWD/internal/catch_test_case_registry_impl.hpp \
    $$PWD/internal/catch_test_case_tracker.hpp \
    $$PWD/internal/catch_test_registry.hpp \
    $$PWD/internal/catch_test_spec.hpp \
    $$PWD/internal/catch_test_spec_parser.hpp \
    $$PWD/internal/catch_text.h \
    $$PWD/internal/catch_timer.h \
    $$PWD/internal/catch_timer.hpp \
    $$PWD/internal/catch_tostring.h \
    $$PWD/internal/catch_tostring.hpp \
    $$PWD/internal/catch_totals.hpp \
    $$PWD/internal/catch_type_traits.hpp \
    $$PWD/internal/catch_version.h \
    $$PWD/internal/catch_version.hpp \
    $$PWD/internal/catch_wildcard_pattern.hpp \
    $$PWD/internal/catch_windows_h_proxy.h \
    $$PWD/internal/catch_xmlwriter.hpp \
    $$PWD/reporters/catch_reporter_automake.hpp \
    $$PWD/reporters/catch_reporter_bases.hpp \
    $$PWD/reporters/catch_reporter_compact.hpp \
    $$PWD/reporters/catch_reporter_console.hpp \
    $$PWD/reporters/catch_reporter_junit.hpp \
    $$PWD/reporters/catch_reporter_multi.hpp \
    $$PWD/reporters/catch_reporter_tap.hpp \
    $$PWD/reporters/catch_reporter_teamcity.hpp \
    $$PWD/reporters/catch_reporter_xml.hpp \
    $$PWD/catch.hpp \
    $$PWD/catch_session.hpp \
    $$PWD/catch_with_main.hpp
